name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      run: actions/checkout@v3

    - name: Build and install Google Test
      run: make
    
    - name: Run Tests
      run: make test
